ROLE_PERMISSION_MAPPING = {
    "admin": [
        "users.add_user",
        "users.change_user",
        "users.delete_user",
        "users.view_user",
        "inventory.add_category",
        "inventory.change_category",
        "inventory.view_category",
        "inventory.add_product",
        "inventory.change_product",
        "inventory.view_product",
        "sales.add_customer",
        "sales.change_customer",
        "sales.view_customer",
        "sales.add_cart",
        "sales.change_cart",
        "sales.view_cart",
    ],
    "manager": [
        "users.view_user",
        "inventory.view_category",
        "inventory.view_product",
        "sales.add_customer",
        "sales.view_customer",
    ],
    "employee": [
        "users.view_user",
        "inventory.view_product",
        "sales.view_customer",
    ],
    "viewer": [
        "users.view_user",
        "inventory.view_product",
    ],
}
