# Generated by Django 6.0.4 on 2026-06-17 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the category", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the category", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "indexes": [
                    models.Index(fields=["name"], name="inventory_c_name_546ce4_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the product", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the product", null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the product",
                        max_digits=10,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock Keeping Unit (SKU) for the product",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category of the product",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity of the product in stock"
                    ),
                ),
                (
                    "min_stock_level",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum stock level to trigger restocking",
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        help_text="Product associated with this stock entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(help_text="Quantity of the product moved"),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("sale", "Sale"),
                            ("sales_return", "Sales Return"),
                            ("purchase_return", "Purchase Return"),
                            ("adjustment", "Adjustment"),
                        ],
                        help_text="Type of stock movement",
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product associated with this stock movement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Unique reference number for this stock take",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this stock take",
                        null=True,
                    ),
                ),
                (
                    "date_taken",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the stock take was completed",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        default="ongoing",
                        help_text="Current status of the stock take",
                        max_length=20,
                    ),
                ),
                (
                    "taken_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the stock take",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_takes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Take",
                "verbose_name_plural": "Stock Takes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockTakeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity of the product counted during stock take"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product associated with this stock take item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_take_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "stock_take",
                    models.ForeignKey(
                        help_text="Stock take this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.stocktake",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Take Item",
                "verbose_name_plural": "Stock Take Items",
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="inventory_p_name_f6a6a1_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="inventory_p_sku_f85905_idx"),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["product"], name="inventory_p_product_35aec0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(
                fields=["min_stock_level"], name="inventory_p_min_sto_bac82e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktake",
            index=models.Index(
                fields=["reference_number"], name="inventory_s_referen_aa18fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktake",
            index=models.Index(
                fields=["-created_at"], name="inventory_s_created_dbcf90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktake",
            index=models.Index(
                fields=["taken_by", "-created_at"],
                name="inventory_s_taken_b_650aa0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktakeitem",
            index=models.Index(
                fields=["stock_take"], name="inventory_s_stock_t_8a88ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktakeitem",
            index=models.Index(
                fields=["product"], name="inventory_s_product_1968c1_idx"
            ),
        ),
    ]
