# Generated by Django 6.0.4 on 2026-06-17 10:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount for the cart",
                        max_digits=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the customer", max_length=255),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the customer",
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the customer",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Address of the customer", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "indexes": [
                    models.Index(fields=["email"], name="sales_custo_email_b3bee2_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "receipt_reference",
                    models.CharField(
                        help_text="Unique reference for the receipt, typically generated based on the sales order",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount for the receipt",
                        max_digits=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes for the receipt",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created the receipt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("ECOCASH", "ECOCASH"),
                            ("CASH", "CASH"),
                            ("TRANSFER", "TRANSFER"),
                        ],
                        help_text="The type of payment (e.g., Ecocash, Cash, Transfer)",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="The amount paid", max_digits=10
                    ),
                ),
                (
                    "denomination",
                    models.CharField(
                        choices=[("USD", "USD"), ("ZWL", "ZWL")],
                        default="USD",
                        help_text="The currency denomination of the payment (e.g., USD, ZWL)",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who recorded the payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        help_text="The receipt this payment is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="sales.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        help_text="Unique order number", max_length=255, unique=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount for the order",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Status of the sales order",
                        max_length=20,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer who placed the order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_orders",
                        to="sales.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created the sales order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Order",
                "verbose_name_plural": "Sales Orders",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "sale_reference_number",
                    models.CharField(
                        help_text="Unique reference number for the sale",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes for the sale", null=True
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer associated with the sale",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="sales.customer",
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        help_text="The receipt associated with the sale",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale",
                        to="sales.receipt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created the sale",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_order",
                    models.OneToOneField(
                        help_text="The sales order associated with the sale",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale",
                "verbose_name_plural": "Sales",
            },
        ),
        migrations.AddField(
            model_name="receipt",
            name="sales_order",
            field=models.ForeignKey(
                help_text="receipt for the sales order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipt",
                to="sales.salesorder",
            ),
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity of the product ordered"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit price of the product",
                        max_digits=10,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product being ordered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_order_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        help_text="The sales order this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Order Item",
                "verbose_name_plural": "Sales Order Items",
            },
        ),
        migrations.CreateModel(
            name="ReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity of the product in the receipt"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit price of the product in the receipt",
                        max_digits=10,
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        help_text="The receipt this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.receipt",
                    ),
                ),
                (
                    "sales_order_item",
                    models.ForeignKey(
                        help_text="The sales order item being included in the receipt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_items",
                        to="sales.salesorderitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity of the product in the cart"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit price of the product in the cart",
                        max_digits=10,
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        help_text="The cart this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product added to the cart",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "sales_order_item",
                    models.OneToOneField(
                        blank=True,
                        help_text="The sales order item created from this cart item (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_item",
                        to="sales.salesorderitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
            },
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["reference_number"], name="sales_cart_referen_caec61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["receipt"], name="sales_payme_receipt_cd34dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["order_number"], name="sales_sales_order_n_78c57a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["customer"], name="sales_sales_custome_b24b56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["customer"], name="sales_sale_custome_f0dcab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["sale_reference_number"], name="sales_sale_sale_re_38d7c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderitem",
            index=models.Index(
                fields=["sales_order"], name="sales_sales_sales_o_d57aa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderitem",
            index=models.Index(
                fields=["product"], name="sales_sales_product_462ddd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart"], name="sales_carti_cart_id_60ed52_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["product"], name="sales_carti_product_e8e565_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("product", "cart"), name="unique_product_in_cart"
            ),
        ),
    ]
