# Generated by Django 6.0.4 on 2026-05-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the record was last updated.",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, help_text="First name", max_length=30, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, help_text="Last name", max_length=30, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address", max_length=254, unique=True
                    ),
                ),
                (
                    "username",
                    models.CharField(help_text="Username", max_length=150, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("employee", "Employee"),
                        ],
                        default="employee",
                        help_text="role of the user in the system",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_user", "Can view user"),
                    ("add_user", "Can add user"),
                    ("change_user", "Can change user"),
                    ("delete_user", "Can delete user"),
                    ("view_user_profile", "Can view user profile"),
                    ("change_user_profile", "Can change user profile"),
                    ("delete_user_profile", "Can delete user profile"),
                ],
            },
        ),
    ]
